name: CH55x Firmware Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SDCC
        run: |
          sudo apt-get update
          sudo apt-get install -y sdcc

      - name: Run compile.sh for reccarz/kw75s
        run: ./compile.sh reccarz/kw75s default

      - name: Upload release with firmware
        uses: ncipollo/release-action@v1
        with:
          tag: reccarz-latest
          artifacts: |
            reccarz_kw75s_default.hex
            reccarz_kw75s_default.bin
          token: ${{ secrets.GH_TOKEN }}
          allowUpdates: true
