name: CH555 Firmware Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sdcc make ripgrep

      - name: Run compile script
        run: bash ./compile.sh reccarz/kw75s default

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ch555-firmware
          path: |
            *.hex
            *.bin
